name: Build, Test, and Audit
on:
  push:
    branches:
      - development
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read  # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'
          
      - name: Build with dotnet
        run: dotnet build --configuration Release
      
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
        
      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
      
      # NuGet package vulnerability scanning using dotnet CLI
      - name: Check for outdated NuGet packages
        run: |
          echo "### Outdated NuGet Packages" >> dependency-report.md
          dotnet list package --outdated >> dependency-report.md
          dotnet list package --outdated >> nuget-outdated.md
        shell: pwsh

      
      # Setup Node.js for npm operations
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      # Install npm dependencies if package.json exists
      - name: Install npm dependencies
        run: |
          if (Test-Path -Path "package.json") {
            npm ci
          } else {
            echo "No package.json found, skipping npm install"
          }
        shell: pwsh
      
      # Run npm audit
      - name: npm audit
        run: |
          if (Test-Path -Path "package.json") {
            npm audit
          } else {
            echo "No package.json found, skipping npm audit"
          }
        shell: pwsh
        continue-on-error: true  # Prevents the workflow from failing if vulnerabilities are found
      # Output outdated NuGet packages to workflow summary
      - name: Output outdated NuGet packages to summary
        run: |
          echo "## Outdated NuGet Packages" >> $GITHUB_STEP_SUMMARY
          if (Test-Path -Path nuget-outdated.md) {
            Get-Content nuget-outdated.md >> $GITHUB_STEP_SUMMARY
          } else {
            echo "No outdated NuGet package report found." >> $GITHUB_STEP_SUMMARY
          }
        shell: pwsh

      # Generate dependency report
      - name: Generate dependency report
        run: |
          echo "### .NET Dependencies" > dependency-report.md
          dotnet list package --include-transitive > dotnet-packages.txt
          Get-Content dotnet-packages.txt >> dependency-report.md
          
          if (Test-Path -Path "package.json") {
            echo "" >> dependency-report.md
            echo "### NPM Dependencies" >> dependency-report.md
            npm list --depth=0 >> npm-packages.txt
            Get-Content npm-packages.txt >> dependency-report.md
            
            echo "" >> dependency-report.md
            echo "### NPM Outdated Packages" >> dependency-report.md
            npm outdated --parseable >> npm-outdated.txt
            Get-Content npm-outdated.txt >> dependency-report.md
          }
        shell: pwsh
        
      # Output vulnerable package report to GitHub Actions summary
      - name: Output NPM vulnerabilities to summary
        run: |
          echo "## NPM Audit Results" >> $GITHUB_STEP_SUMMARY
          $audit = npm audit --json | ConvertFrom-Json
          if ($audit.metadata.vulnerabilities) {
            $vuln = $audit.metadata.vulnerabilities
            echo "Found $($vuln.info + $vuln.low + $vuln.moderate + $vuln.high + $vuln.critical) vulnerabilities:" >> $GITHUB_STEP_SUMMARY
            echo "- Critical: $($vuln.critical)" >> $GITHUB_STEP_SUMMARY
            echo "- High: $($vuln.high)" >> $GITHUB_STEP_SUMMARY
            echo "- Moderate: $($vuln.moderate)" >> $GITHUB_STEP_SUMMARY
            echo "- Low: $($vuln.low)" >> $GITHUB_STEP_SUMMARY
            echo "- Info: $($vuln.info)" >> $GITHUB_STEP_SUMMARY
          } else {
            echo "No vulnerabilities found." >> $GITHUB_STEP_SUMMARY
          }
        shell: pwsh

        continue-on-error: true
